export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILS = 'FETCH_INGREDIENTS_FAILS';

export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES';
export const PURCHASE_BURGER_FAILS = 'PURCHASE_BURGER_FAILS';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_FAILS = 'FETCH_ORDER_FAILS';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const SET_ORDERS = 'SET_ORDERS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCES = 'AUTH_SUCCES';
export const AUTH_FAILS = 'AUTH_FAILS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

